
services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - 8222:8222
      - 4222:4222

  orders-db:
    image: postgres:16
    container_name: orders_postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    restart: always

  orders-ms:
    container_name: orders_ms
    depends_on:
      - nats-server
      - orders-db
      - products-ms
    build: ./orders-ms
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - PRODUCTS_SERVICE_PORT=3001
      - PRODUCTS_SERVICE_HOST=products-ms
      - DATABASE_URL=postgresql://postgres:postgres@orders-db:5432/orders_db?schema=public
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev

  products-ms:
    container_name: products_ms
    depends_on:
      - nats-server
    build: ./products-ms
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev

  api-gateway:
    container_name: api_gateway
    depends_on:
      - nats-server
      - products-ms
    build: ./api-gateway
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - PRODUCTS_MICROSERVICE_HOST=products-ms
      - PRODUCTS_MICROSERVICE_PORT=3001
      - ORDERS_MICROSERVICE_HOST=orders-ms
      - ORDERS_MICROSERVICE_PORT=3002
    ports:
      - ${API_GATEWAY_PORT}:3000
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev

  payments-ms:
    container_name: payments_ms
    depends_on:
      - nats-server
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    build: ./payments-ms
    environment:
      - PORT=${PAYMENTS_PORT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - API_GATEWAY=${API_GATEWAY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    command: npm run start:dev
    ports:
      - ${PAYMENTS_PORT}:3003

  auth-ms:
    container_name: auth_ms
    depends_on:
      - nats-server
    build: ./auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev